"""
Django settings for django_demo project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1f5(wl%juev_#6@=7xe6+kojmy9s*f9nfb%&n6edi8ajjc*bzx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allows access to the project address list
# If set to null, it can only be accessed natively
# If it is allowed to be accessed by an external machine, it can be written as ['*'] here.
# start with ./manage.oy runserver 0.0.0.0:8000
ALLOWED_HOSTS = ['*']


# Application definition
# Sign up for applications in Django
# Applications need to be created, registered and then used
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news',
    'music',
    'sport',
    'index',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Specifies the main routing profile for the project
ROOT_URLCONF = 'django_demo.urls'

TEMPLATES = [
    {
        # 指定使用模板的引擎
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 指定存放模板的文件夹
        # 将所有的模板都保存在 项目的 templates 文件夹中
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # 制定是否要搜索应用(app)中的模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/


# Language Settings, change the value to zh-Hans if you need to convert the project to Chinese
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

# Specify the time zone and change the value to Asia/Shanghai if it is set to China time zone
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# 
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
# 静态文件访问路径
STATIC_URL = '/static/'

# 静态文件存储路径
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)