# Generated by Django 2.1.7 on 2019-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190424_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publishers',
            field=models.ManyToManyField(to='index.Publisher'),
        ),
    ]
