"""empty message

Revision ID: 59e4e5b58da1
Revises: f787b7031510
Create Date: 2019-04-11 10:56:20.182019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e4e5b58da1'
down_revision = 'f787b7031510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wife', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'wife', ['uid'])
    op.create_foreign_key(None, 'wife', 'users', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wife', type_='foreignkey')
    op.drop_constraint(None, 'wife', type_='unique')
    op.drop_column('wife', 'uid')
    # ### end Alembic commands ###
