"""empty message

Revision ID: 8dd765422285
Revises: bbedbaae3405
Create Date: 2019-04-11 11:15:41.081325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd765422285'
down_revision = 'bbedbaae3405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wife_age', table_name='wife')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wife_age', 'wife', ['age'], unique=False)
    # ### end Alembic commands ###
