"""empty message

Revision ID: b2a187f85d06
Revises: 15beda253d41
Create Date: 2019-04-11 14:58:50.198086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a187f85d06'
down_revision = '15beda253d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student_course', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'student_course', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    # ### end Alembic commands ###
