"""empty message

Revision ID: bbedbaae3405
Revises: 59e4e5b58da1
Create Date: 2019-04-11 11:15:10.718143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbedbaae3405'
down_revision = '59e4e5b58da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wife_age'), 'wife', ['age'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wife_age'), table_name='wife')
    # ### end Alembic commands ###
