# Generated by Django 2.1.7 on 2019-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='姓名')),
                ('upwd', models.CharField(max_length=30, verbose_name='密码')),
                ('uage', models.IntegerField(verbose_name='年龄')),
                ('uemial', models.EmailField(max_length=200, verbose_name='邮箱')),
            ],
        ),
    ]
