"""empty message

Revision ID: d9315e7c370c
Revises: f20200d1696a
Create Date: 2019-04-15 15:35:30.121744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9315e7c370c'
down_revision = 'f20200d1696a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=80), nullable=False),
    sa.Column('upwd', sa.String(length=20), nullable=False),
    sa.Column('uphone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uphone')
    )
    op.create_index(op.f('ix_user_uname'), 'user', ['uname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uname'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
